name: Publish2 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./WebApplication2/WebApplication2.sln
        
      - name: Build
        run: dotnet build .WebApplication2/WebApplication2.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish .WebApplication2/WebApplication2.sln --configuration Release --no-build 
