name: Publish1 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - feature


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./ASPWebapplication/ASPWebapplication/ASPWebapplication.csproj
        
      - name: Build
        run: dotnet build ./ASPWebapplication/ASPWebapplication/ASPWebapplication.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./ASPWebapplication/ASPWebapplication/ASPWebapplication.csproj --configuration Release --no-build 
